apiVersion: v2
# The name of your application
name: euc-middleware
# A brief description of your application
description: A Helm chart to deploy EUC-Middleware service to a Kubernetes cluster

# Chart type: application or library
# - application: deployable application charts
# - library: common utility functions/templates
type: application

# Chart version (follows Semantic Versioning)
# Increment this when you modify the chart structure/templates
version: 0.1.0

# Application version
# This is the version of your actual application
appVersion: "1.0.0"

# Dependencies on other charts (if any)
dependencies:
  - name: mongodb
    version: ">16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

# Keywords describing your application
keywords:
  - EUC-Middleware
  - middleware

# Home page of your application
home: https://github.com/nstarx-org/EUC_Workbench

# Chart maintainers
maintainers:
  - name: Anand Kumar
    email: anand.kontham@nstarxinc.com

# Icon for your application (optional)
# icon: https://your-icon-url.svg