apiVersion: v2
# The name of your application
name: genai-lab-3-report-generator-api
# A brief description of your application
description: A Helm chart for deploying the genai-lab-3-report-generator-api application.

# Chart type: application or library
# - application: deployable application charts
# - library: common utility functions/templates
type: application

# Chart version (follows Semantic Versioning)
# Increment this when you modify the chart structure/templates
version: 0.1.1

# Application version
# This is the version of your actual application
appVersion: "0.1.1"

# Keywords describing your application
keywords:
  - report-generator-api
  - genai-lab-3

# Home page of your application
home: https://github.com/nstarx-org/GenAI-Lab-3

# Chart maintainers
# maintainers:
#  - name: Your Name
#    email: your.email@example.com

# Icon for your application (optional)
# icon: https://your-icon-url.svg
