apiVersion: v2
# The name of your application
name: genai-hub-blueprint-ai
# A brief description of your application
description: A Helm chart for deploying blueprint ai usecase for the genai-hub

# Chart type: application or library
# - application: deployable application charts
# - library: common utility functions/templates
type: application

# Chart version (follows Semantic Versioning)
# Increment this when you modify the chart structure/templates
version: 0.1.0

# Application version
# This is the version of your actual application
appVersion: "0.1.0"

# Keywords describing your application
keywords:
  - blueprint-ai

# Home page of your application
home: https://github.com/nstarx-org/ML-Service-BlueprintAI

# Chart maintainers
# maintainers:
#  - name: Your Name
#    email: your.email@example.com

# Icon for your application (optional)
# icon: https://your-icon-url.svg