name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write    # Needed for pushing to gh-pages and creating releases
  pages: write       # Needed for GitHub Pages
  id-token: write    # Needed for requesting the JWT

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add Helm dependencies (if needed)
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          # Add other dependencies your charts might need
          
      # Synchronize templates before packaging
      - name: Sync Templates to Charts
        run: |
          # Create templates directory in each chart
          for app in charts/*/; do
            mkdir -p "${app}templates"
          done
          
          # Copy templates to each chart's templates directory
          for app in charts/*/; do
            cp -r templates/* "${app}templates/"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true